name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "*"

jobs:
  evaluate-label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.label_step.outputs.main}}
    steps:
      - name: checks for the label
        id: label_step
        run: |
          if [[ "${{ github.ref  }}" == "refs/heads/main" ]]; then # TODO: modify the branch after merging
                echo "version=latest" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ github.ref_type }}" == "branch" ]] && [[ "${{ github.ref  }}" != "refs/heads/main" ]]; then # TODO: modify the branch after merging
                exit 1
          fi
          if [[ "${{ github.ref_type }}" == "tag" ]]; then 
                echo "version=stable" >> $GITHUB_OUTPUT
          fi

  deploy-docs:
    needs: [evaluate-label]
    uses: qiboteam/workflows/.github/workflows/deploy-ghpages-latest-stable.yml@main
    with:
      python-version: 3.9
      package-manager: "poetry"
      dependency-path: "**/poetry.lock"
      trigger-label: "${{needs.evaluate-label.outputs.label}}"
      docs-folder: qibocal
